config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'doctors#index'

  # resources :doctors, only: [:create]
  resources :doctors, only: [:index, :show, :new, :create] do
    resources :timeslots, only: [:index, :new, :create, :show] do
      resources :appointments, only: [:new, :create, :index, :show]
    end
  end
  resources :patient, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :timeslot, validate: false

  accepts_nested_attributes_for :patient

  validates :doctor, :patient, :timeslot, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients, through: :appointments
  has_many :appointments
  has_many :timeslots, validate: false
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
  has_many :timeslots
  validates :name, :surname, :birthdate, presence: true
  validates_uniqueness_of :name, scope: %i[surname birthdate]
end

app/models/timeslot.rb
require 'date'

class Timeslot < ApplicationRecord
  belongs_to :doctor
  belongs_to :appointment, optional: true

  validates_uniqueness_of :app_time, scope: %i[app_date doctor_id]
  validate :lunch?, :weekend?
  validates_time :app_time, between: ['9:00', '17:00']
  validates_date :app_date, after: Date.today
  # def to_param
  #   app_date
  # end

  private

  def lunch?
    if app_time.strftime('%H') == '13'
      errors.add(:app_time, "it's time for doctor's lunch")
    end
  end

  def weekend?
    if app_date.strftime('%u') == '6' || app_date.strftime('%u') == '7'
      errors.add(:app_date, "The clinics doesn't work at weekend")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def show
  end

  # GET /appointments/new
  def new
    # binding.pry
    @doctor = Doctor.find(params[:doctor_id])
    # @doctor = Doctor.find_by(id: params[:doctor_id])
    @timeslot = @doctor.timeslots.find(params[:timeslot_id])
    # @appointment = Appointment.new(doctor_id: @doctor.id, timeslot: @timeslot)
    @appointment = @doctor.appointments.new
    # @appointment = Appointment.find(params[:id])
    @appointment.build_patient
    # binding.pry
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    # binding.pry
    @doctor = Doctor.find(params[:doctor_id])
    patient = Patient.where(
      name: params[:patient][:name],
      surname: params[:patient][:surname], birthdate: params[:patient][:birthdate]
      ).first_or_create
      # birthdate: "#{params[:patient][:"birthdate(1i)"]}.#{params[:patient][:"birthdate(2i)"]}.#{params[:patient][:"birthdate(3i)"]}"

    timeslot = Timeslot.find_by(id: params[:timeslot_id])
    appointment = Appointment.create(
      doctor_id: params[:doctor_id], timeslot: timeslot, patient_id: patient.id
      ) if (timeslot.app_date >= Date.today && timeslot.app_time > Time.now.hour)

    if appointment.save
      timeslot.update_attribute(:status, true)
      # appointment.timeslot.status = true
      redirect_to @doctor, notice: 'Appointment was successfully created'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def appointment_params
    #   params.require(:appointment).permit(:doctor_id, :timeslot_id, patient_attributes: [:name, :surname, :birthdate])#(:appointment_date, :doctor_id, :patient_id, :timeslot_id)
    # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @timeslots = Timeslot.where(doctor_id: @doctor.id)
    @timeslots = @timeslots.select { |t| t.status == nil }
    # @same_dates = []
    # @timeslots.each { |t| @same_dates << t.app_date }
    # @same_dates = @same_dates.uniq
    @appointment = @doctor.appointments.build#(doctor_id: @doctor.id, appointment_date: )
    # while @same_dates.app_date.uniq do
    #   @timeslots.each { |t| same_dates << t.app_date}
    # end

    # binding.pry
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    # respond_to do |format|
    #   if @doctor.save
    #     format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
    #     format.json { render :show, status: :created, location: @doctor }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @doctor.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.fetch(:doctor, {})
    end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :set_timeslot, only: [:show, :edit, :update, :destroy]

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
  end

  # GET /timeslots/new
  def new
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)

    # respond_to do |format|
    #   if @timeslot.save
    #     format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
    #     format.json { render :show, status: :created, location: @timeslot }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @timeslot.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /timeslots/1
  # PATCH/PUT /timeslots/1.json
  def update
    respond_to do |format|
      if @timeslot.update(timeslot_params)
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeslot }
      else
        format.html { render :edit }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot.destroy
    respond_to do |format|
      format.html { redirect_to timeslots_url, notice: 'Timeslot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeslot_params
      params.fetch(:timeslot, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for [:doctor, :timeslot, @appointment] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

	  <div class="form-inputs">
		  <%= simple_fields_for :patient do |p|%>
		  	<%= p.input :name %>
		  	<%= p.input :surname %>
		  	<%= p.input :birthdate, as: :string, input_html: {type: :date} %>
		  <% end %>
	  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to doctor.specialization, doctor %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Доступное для записи время</h3>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= link_to "#{timeslot.app_date.strftime('%d %m, %A')}" "#{ timeslot.app_time.strftime("%H:%M")}", new_doctor_timeslot_appointment_path(@doctor, timeslot, @appointment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Clinica2" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Clinica2</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/timeslots/_form.html.erb
<%= simple_form_for(@timeslot) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing Timeslot</h1>

<%= render 'form', timeslot: @timeslot %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timeslots</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= link_to 'Show', timeslot %></td>
        <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
        <td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeslot', new_timeslot_path %>

app/views/timeslots/new.html.erb
<h1>New Timeslot</h1>

<%= render 'form', timeslot: @timeslot %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p id="notice"><%= notice %></p>